POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Amal Saleh",
  "email": "amal2@email.com",
  "password_plain": "senha123"
}

### Rota de Autenticação (Login)
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "amal@email.com",
  "password_plain": "senha123"
}
