### ==========================================
### ETAPA 1 e 2: USUÁRIOS E AUTENTICAÇÃO
### ==========================================

### Cadastro de Comerciante
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Amal Saleh",
  "email": "amal2@email.com",
  "password_plain": "senha123"
}

###

### Rota de Autenticação (Login)
# @name login
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "amal@email.com",
  "password_plain": "senha123"
}

###

### 🔑 VARIÁVEL GLOBAL DO TOKEN (Atualize aqui quando expirar)
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW1hbCBTYWxlaCIsImVtYWlsIjoiYW1hbEBlbWFpbC5jb20iLCJpYXQiOjE3ODMyMTMwMTIsImV4cCI6MTc4MzI5OTQxMiwic3ViIjoiYmI4MWEyN2YtMjE3Yy00YWE1LThlMzUtMzY4NTk1M2YyOGVjIn0.jZtRRHUwRdDwabrQYpXvjUp9GdxNtP51M98GwV_vxJw

### ==========================================
### ETAPA 3: PRODUTOS (ROTAS PROTEGIDAS)
### ==========================================

### Cadastro de Produto - PROTEGIDA
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Camiseta Algodão Premium V2",
  "description": "Camiseta 100% algodão com proteção JWT",
  "price": 99.90,
  "stock_quantity": 30
}

###

### Listagem de Produtos - PROTEGIDA
GET http://localhost:3000/products
Authorization: Bearer {{token}}

###

### ==========================================
### ETAPA 4: TRANSAÇÕES FINANCEIRAS E CHECKOUT
### ==========================================

### Registrar uma Nova Venda com Sucesso
POST http://localhost:3000/sales
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "customer_name": "Maria do Bolo",
  "items": [
    {
      "product_id": "ec82755b-b9ed-44b0-b2f6-eab424849fb3",
      "quantity": 2
    }
  ]
}

###

### Testar Erro: Venda com Estoque Insuficiente
POST http://localhost:3000/sales
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "customer_name": "Cliente Teste Erro",
  "items": [
    {
      "product_id": "ec82755b-b9ed-44b0-b2f6-eab424849fb3",
      "quantity": 99999
    }
  ]
}

### ==========================================
### 📊 ETAPA 5: HISTÓRICO E MÉTRICAS
### ==========================================

### Listar Histórico de Vendas
GET http://localhost:3000/sales
Authorization: Bearer {{token}}

###

### Obter Dashboard de Insights Financeiros
GET http://localhost:3000/sales/metrics
Authorization: Bearer {{token}}
